name: Style-test-coverage
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: "Install black"
        run: pip install black
      - name: "Black check"
        run: black --check .
  test:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-python@v4
           with:
             python-version: '3.8'
         - name: "Install dependencies"
           run: |
             pip install -U coverage
             pip install -U pytest
             pip install -r requirements.txt
         - name: "Coverage"
           run: coverage run -m pytest
         - name: "Archive code coverage results"
           uses: actions/upload-artifact@v3
           with:
             name: code-coverage-report
             path: .coverage
             retention-days: 1
